language: node_js
node_js:
  - '12'
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: public
  target_branch: gh-pages
  on:
    branch: master