version: "3.4"
services:
  www:
    image: "node:lts"
    command: yarn start
    volumes:
      - ../:/app
      - $HOME/.ssh:/root/.ssh
    restart: on-failure
    working_dir: "/app"
    ports:
      - "3000:3000"

  build:
    image: "node:lts"
    volumes:
      - $HOME/.ssh:/root/.ssh
      - $HOME/.gitconfig:/root/.gitconfig
      - ../:/app
    working_dir: "/app"
